### PR TITLE
Issue#86 System details Export

### LINKED ISSUE #86: Make system info exportable as PDF/PNG
It would be cool if one could press on an export button in the info page to receive a PDF/PNG/Html export of his system specs

grafik

Idea comes from @madsrh somewhere in the chat

### PR DESCRIPTION
**Pull request by Chandram-Dutta**
Added System Info Download Functionality

Packages Added:
- pdf
- path_provider
- open_file

Assets Added:
- pdfAssets/COF Logo

After clicking on the System Data Outlined Button, a snackbar appears which has an action to open the PDF.
Info Area
PDF

I am using Debian 11 as I am waiting for Ubuntu 21.10 to be released😅

Closes #86

### CODE REVIEW

**Comment by Jupi007** [comment]
Looks very nice :)

Personally I would prefer have the button at the far bottom of the page. What do you think of @Feichtmeier ?

**Comment by Muqtxdir** [comment]
little nitpick, I don't think the wording seems correct. maybe **export** would seem much better

**Comment by Chandram-Dutta** [comment]
> I think "Export" would be a more appropriate button label, and yeah, I agree with @Jupi007 that it should be something less prominent considering how common action it would be for users to export these PDFs... :)

Yup...ill put in the bottom right corner then😀

**Comment by Chandram-Dutta** [comment]
Ok.. I have shifted the button to the bottom.. however I am not able to position it in the right with proper alignment to the SettingsSection Widget
Screenshot from 2021-10-06 16-36-11

**Comment by Chandram-Dutta** [comment]
> @Chandram-Dutta Did you tried to wrap the `OutlinedButton` inside a `SizedBox` and then inside an `Align` widget like this:
> 
> ```dart
> SizedBox(
>   width: 500,
>   child: Align(
>     alignment: Alignment.topRight,
>     child: OutlinedButton(
>       child: Text("Export"),
>       ...
>     ),
> )),
> ```

Will try it...I was trying to use positioned. ..

**Comment by Chandram-Dutta** [comment]
> What is _System Data_? :P Is it the _Info_ on the screen or something else? As said, I'd call the button _Export_ because a) the rest is obvious from the context, b) to make the button less massive, and c) using different terms for the same thing only causes confusion anyway.

Only "Export" may cause confusion

Anyway...ig we have 3 option
- "Export"
- "Export System Data"
- "Export System Info"

Would like everyone to suggest which would be the best...😁

**Comment by Feichtmeier** [comment]
Nice idea with the download button. Since everything in the page looks lind of in-active, I would use an ElevatedButton for the download button. Could be small but green ElevatedButton

**Comment by Chandram-Dutta** [comment]
The icon used in geary to forward mails could be used

**Pull request merged**
