### PR TITLE
Add Nightlight page

### PR DESCRIPTION
**Pull request by YoussefLasheen**
Add Nightlight page

Ref #58

### CODE REVIEW

**Comment by YoussefLasheen** [comment]
There some missing features. 

- [ ] Active time for the nightlight. I am not sure what style to use i thought of using SpinBoxes like in the multitasking page but I am not sure yet
- [ ] Localization for the strings in the page
- [ ] Copy the style of slider of gnome settings (with gradients)

**Comment by YoussefLasheen** [comment]
@Feichtmeier I need your input please.

**Comment by Feichtmeier** [comment]
@YoussefLasheen thanks, a bit hard to say without screenshots :) I need to check it out locally otherwise. I hope I have time for this tomorrow
Generally, do not think too much about styling, we can fix this later
Thank you for taking the time to work on this!

**Comment by YoussefLasheen** [comment]
image
Added the active time selector for night mode

**Review by Feichtmeier — APPROVED** [review]
Thank you very much!

**Pull request merged**
