### PR TITLE
Reverts exception catching part of #254

### PR DESCRIPTION
**Pull request by Feichtmeier**
@Jupi007 could you test once and confirm that the exception catching is not needed?
For me it works for screen brightness

### CODE REVIEW

**Comment by mivoligo** [comment]
Without catching the exception, I can't move the screen brightness slider.

**Comment by Jupi007** [comment]
For me both sliders are still disabled, which is the correct behaviour.

**Comment by mivoligo** [comment]
This branch:
this-branch


Master:

master

**Comment by Feichtmeier** [comment]
STrange! I can move the slider and the brightness changes as expected :thinking: 
(at the end of the clip I close the lid and it turns grey)
ya

**Comment by mivoligo** [comment]
It's because you have working keyboard brightness. I don't have that option so when I move the screen brightness slider it throws exception about missing keyboard brightness.

**Comment by Feichtmeier** [comment]
You are right! ANd I think I found the problem. 
In the power settings service two instances of the class Brightness are created. One for the path "Screen" and one for the path "Keyboard"
But the getBrightness method does only lookup the interace org.gnome.SettingsDeamon.Power and I don't think it takes the path

**Comment by Feichtmeier** [comment]
ya

Every time you change one Brightness, both objects are triggered...
I try to fix this service

**Comment by Feichtmeier** [comment]
Alright can you check again? I think this could be the fix :)

**Comment by mivoligo** [comment]
Sadly not working for me. As soon as I open the Power page I get this error:
```Launching lib/main.dart on Linux in debug mode...
Building Linux application...
Debug service listening on ws://127.0.0.1:36119/q18egreVRfk=/ws
Syncing files to device Linux...
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: org.freedesktop.DBus.Error.Failed: Failed to get property Brightness on interface org.gnome.SettingsDaemon.Power.Keyboard
#0      DBusClient._callMethod (package:dbus/src/dbus_client.dart:1111:13)
<asynchronous suspension>
#1      DBusClient.callMethod (package:dbus/src/dbus_client.dart:628:12)
<asynchronous suspension>
#2      DBusRemoteObject.getProperty (package:dbus/src/dbus_remote_object.dart:126:18)
<asynchronous suspension>
#3      _BrightnessObject.getBrightness (package:settings/services/power_settings_service.dart:88:9)
<asynchronous suspension>
#4      Brightness._initBrightness (package:settings/services/power_settings_service.dart:69:23)
<asynchronous suspension>
#5      Brightness.init (package:settings/services/power_settings_service.dart:35:5)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:473:21)
<asynchronous suspension>
#7      Future.wait.<anonymous closure> (dart:async/future.dart:473:21)
<asynchronous suspension>```

**Comment by Feichtmeier** [comment]
@mivoligo hmmm

could install "d-feet" (`sudo apt install d-feet`) and look in the session bus for "org.gnome.SettingsDaemon.Power" and see if dbus checks whether you have a keyboard with brightness or not? I mean if the Keyboard and Screen paths are there for you?

**Comment by mivoligo** [comment]
Screenshot from 2022-01-19 13-56-23

**Comment by Feichtmeier** [comment]
Thanks, any changes after the last commit? :(

**Comment by mivoligo** [comment]
Unfortunately no :( Screen brightness changes but the slider is not moving.

**Comment by Feichtmeier** [comment]
Alright! Before I ask you over and over I will set up a regular PC and test this myself! Thanks so far ❤️

**Pull request closed without merging**
